dist: xenial
env:
  global:
   - COMMIT=${TRAVIS_COMMIT::6}
   - REPO=atulabhi/hostname;
jobs:
  include:
    - stage: build docker image
      if: branch = main
      script: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . && docker push $REPO:$TRAVIS_BRANCH-$COMMIT; 
    - stage: test
      script: ./test.sh
