- hosts: all
  become: yes
  become_method: sudo
  vars:
    kubectl_version: 1.18.6
    docker_version: 19.03.11
  tasks:

    - name: install system updates
      apt: name=* state=latest update_cache=yes


    - name: disable swap permanently
      lineinfile:
        path: /etc/fstab
        regexp: '^[^#].*swap.*$'
        state: absent

    - name: delete swapfile
      file:
        path: /swapfile
        state: absent

    - name: install prerequisites
      apt:
        name: [ vim, conntrack, socat, lvm2, telnet, tcpdump ]

    - name: download minikube latest version
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
  
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
  
    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: set bridge-nf-call-iptables = 1
      lineinfile:
        path: /etc/sysctl.conf
        line: net.bridge.bridge-nf-call-iptables = 1

    - name: apply sysctl config
      shell: sysctl -p

    - name: start minikube
      shell: minikube start --vm-driver=none

    - name: Add service-node-port-range parameter to minikube config file
      lineinfile:
        state: present
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        line: '    - --service-node-port-range=1024-65535'
        insertafter: '^.*service-account-key-file.*$'

    - name: start and enable kubelet service
      service:
        name: kubelet
        enabled: yes
        state: started
    
    - name: create dir /home/vagrant/bin
      file:
        path: /home/vagrant/bin
        state: directory

    - name: Download  kubectl 
      get_url:
        url: https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
    - name: change kubectl  executable ownership to vagrant
      file:
        path: /usr/local/bin/kubectl
        mode: 0755
        owner: vagrant
        group: vagrant

    - name: copy kubectl conf
      copy:
        src: /root/.kube
        dest: /home/vagrant/
        remote_src: yes
        owner: vagrant
        group: vagrant

    - name: fix kubectl conf
      replace:
        path: /home/vagrant/.kube/config
        regexp: '/root'
        replace: '/home/vagrant'

    - name: enable kubectl autocompletion
      lineinfile:
        path: /home/vagrant/.bashrc
        line: source <(kubectl completion bash)
        insertafter: EOF

    - name: enable kubectl alias k
      lineinfile:
        path: /home/vagrant/.bashrc
        line: alias k="kubectl"
        insertafter: EOF

    - name: enable kubectl alias kc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: alias kc="kubectl"
        insertafter: EOF

    - name: copy minikube conf
      copy:
        src: /root/.minikube
        dest: /home/vagrant/
        remote_src: yes
        owner: vagrant
        group: vagrant

    - name: create /vagrant directory
      file:
        path: /vagrant
        state: directory

    - name: Install and enable kubernetes dashboard components
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
      #shell: sudo kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml

    #- name: Install Kubernetes Ingress components
    #  shell: sudo kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
          
    - name: Create dashboard admin user
      shell: kubectl apply -f /vagrant/dashboard-adminuser.yaml

    - name: Create Directory for basic Start page
      file:
        path: /home/vagrant/minikube
        state: directory

    - name: Copy Start Page for Easy Testing
      copy:
        src: index.html
        dest: /home/vagrant/minikube/index.html
        owner: vagrant
        group: vagrant
        
    - name: Start kubectl proxy 
      shell: "nohup kubectl proxy --address='0.0.0.0' –port=8001 --www=/home/vagrant/minikube --www-prefix=/minikube/"
      async: 100
      poll: 0
      register: start_kube_proxy

    - name: Check kubectl proxy output
      debug:
        msg: "{{ start_kube_proxy }}"

    - name: Get Secret to Authenticate to kubernetes dashboard
      shell: "kubectl -n kube-system get secret | grep default-token | awk '{print $1}'"
      register: get_token

    - name: Extract secret name
      set_fact:
        KUBE_TOKEN: "{{ get_token.stdout }}"

    - name: Get Token to Authenticate to kubernetes dashboard
      shell: "kubectl -n kube-system describe secret {{ KUBE_TOKEN }} | grep token: | awk '{print $2}'"
      register: get_token_value
    
    - name: Access Below URL from your Host machine browser
      debug:
        msg: "http://localhost:8001/minikube/"
  
    - name: Use below token to authenticate in kubernetes dashboard"
      debug:
        msg: "{{ get_token_value.stdout }}"