- hosts: all
  become: yes
  become_method: sudo
  vars:
    kubectl_version: 1.18.6
    docker_version: 19.03.11
  tasks:

    - name: install system updates
      apt: name=* state=latest update_cache=yes


    - name: disable swap permanently
      lineinfile:
        path: /etc/fstab
        regexp: '^[^#].*swap.*$'
        state: absent

    - name: delete swapfile
      file:
        path: /swapfile
        state: absent

    - name: install prerequisites
      apt:
        name: [ vim, conntrack, socat, lvm2, telnet, tcpdump ]

    - name: download minikube latest version
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
  
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
  
    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: set bridge-nf-call-iptables = 1
      lineinfile:
        path: /etc/sysctl.conf
        line: net.bridge.bridge-nf-call-iptables = 1

    - name: apply sysctl config
      shell: sysctl -p

    - name: start minikube
      shell: minikube start --vm-driver=none

    - name: Add service-node-port-range parameter to minikube config file
      lineinfile:
        state: present
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        line: '    - --service-node-port-range=1024-65535'
        insertafter: '^.*service-account-key-file.*$'

    - name: start and enable kubelet service
      service:
        name: kubelet
        enabled: yes
        state: started
    
    - name: create dir /home/vagrant/bin
      file:
        path: /home/vagrant/bin
        state: directory

    - name: Download  kubectl 
      get_url:
        url: https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
    - name: change kubectl  executable ownership to vagrant
      file:
        path: /usr/local/bin/kubectl
        mode: 0755
        owner: vagrant
        group: vagrant

    - name: copy kubectl conf
      copy:
        src: /root/.kube
        dest: /home/vagrant/
        remote_src: yes
        owner: vagrant
        group: vagrant

    - name: fix kubectl conf
      replace:
        path: /home/vagrant/.kube/config
        regexp: '/root'
        replace: '/home/vagrant'
      